name: error_or_result
description: Helper classes that returns a Result or Errors objects to reduce amount of exception throwing.
version: 1.0.0
# homepage: https://www.example.com
repository: https://github.com/vaygeth89/error_or_result
publisher: https://github.com/vaygeth89

environment:
  sdk: ">=2.17.6<3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
